In [1]:
import pandas as pd
import numpy as np


testing_DF = pd.DataFrame({'t1':[1, 0, 0, 0], \
                          't2':[1, 1, 1, 1], \
                          't3':[1, 2, 4, 8], \
                          't4':[1, 3, 9, 27]})



np_arr = testing_DF.values
time = np_arr
# P already Normalized
pd.DataFrame(np.dot(np.linalg.inv(np.linalg.cholesky(np.dot(time, time.T)).T).T, time))

0         1         2         3
0  0.500000  0.500000  0.500000  0.500000
1 -0.670820 -0.223607  0.223607  0.670820
2  0.500000 -0.500000 -0.500000  0.500000
3 -0.223607  0.670820 -0.670820  0.223607

## Example

In [2]:
import pandas as pd
import numpy as np

# data = pd.read_csv('../ANOVA_Approaches_to_Longitudinal_Data/VocabGrowth.csv', header=None)
# data.head()

data = pd.read_csv('../ANOVA_Approaches_to_Longitudinal_Data/VocabGrowth.csv', \
                   names = ['8_Grade', '9_Grade', '10_Grade', '11_Grade'])
VocabGrowth = data

In [3]:
y_bar_dot = VocabGrowth.mean()
y_bar_dot

8_Grade     1.137500
9_Grade     2.541719
10_Grade    2.988281
11_Grade    3.468750
dtype: float64

In [4]:
# Orthoginal Matrix
# P already Normalized
P = pd.DataFrame(np.dot(np.linalg.inv(np.linalg.cholesky(np.dot(time, time.T)).T).T, time))
P

0         1         2         3
0  0.500000  0.500000  0.500000  0.500000
1 -0.670820 -0.223607  0.223607  0.670820
2  0.500000 -0.500000 -0.500000  0.500000
3 -0.223607  0.670820 -0.670820  0.223607

In [5]:
# Orthogonal Polynomial Estimates
np.dot(P, y_bar_dot)

array([ 5.068125  ,  1.66370445, -0.461875  ,  0.22172012])

In [6]:
# Y is the (N x n) matrix of all data
Y = VocabGrowth
Yt_Y = np.dot(Y.T, Y)
Yt_Y

array([[ 307.8958,  386.1704,  441.3901,  432.475 ],
       [ 386.1704,  687.3115,  709.6184,  755.9904],
       [ 441.3901,  709.6184,  867.8297,  876.6472],
       [ 432.475 ,  755.9904,  876.6472, 1003.9108]])

In [21]:
len(Y)*np.dot(y_bar_dot, y_bar_dot.T)

1837.842678125

In [20]:
SSR_r = np.dot(np.dot(P, np.subtract(Yt_Y, len(Y)*np.dot(y_bar_dot, y_bar_dot.T))), P.T)
SSR_r

array([[-4833.4880125 ,   543.32773521,  -199.40535   ,    48.2887824 ],
       [  543.32773521,   227.51182   ,   -37.09949824,    20.46799   ],
       [ -199.40535   ,   -37.09949824,    57.6846    ,   -10.63663996],
       [   48.2887824 ,    20.46799   ,   -10.63663996,    63.86868   ]])

In [24]:
SST_t = len(Y) * np.dot(np.dot(P, np.dot(y_bar_dot, y_bar_dot.T)), P.T)
SST_t

array([[ 1.83784268e+03, -1.13686838e-13, -6.25277607e-13,
         2.44426701e-12],
       [-1.13686838e-13,  1.83784268e+03,  5.68434189e-13,
        -2.04636308e-12],
       [-6.25277607e-13,  5.68434189e-13,  1.83784268e+03,
        -1.18234311e-11],
       [ 2.44426701e-12, -2.04636308e-12, -1.17097443e-11,
         1.83784268e+03]])

In [13]:
MANOVA_table_dict = {'Source':['Time', 'Residual', 'Total'], \
                     'df': [1, len(Y) - 1, len(Y)], \
                     'SSCP': []
                     
                    }